# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

agent_name: 'goes_fiscal_agent'
agent_display_name: 'Fiscal Agent Gobierno de El Salvador'
agent_description: 'Useful agent to support El Salvador government fical analysts to identify insights and trends in data.'

deploy:
  dependencies: ['google-cloud-aiplatform[agent_engines,adk]', 'google-adk', 'cloudpickle', 'pydantic', 'google-cloud-bigquery', 'pandas', 'db-dtypes', 'pyyaml']